### ISSUE TITLE
If handle_always_visible is disabled, the start and end of progress are not displayed correctly

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#239]
### Reproduction Steps

See https://github.com/Samillion/ModernZ/issues/239#issuecomment-2565767127

**Comment by Samillion** [comment]
CC @Commander07

**Comment by Samillion** [comment]
@Xurdejl terribly sorry, forgot to CC you as well.

**Comment by Keith94** [comment]
I came across an interesting line dealing with `progress_offset`:

https://github.com/Samillion/ModernZ/blob/06cc6515f0ff000a988cb5a735d914b0aec91991/modernz.lua#L988

So I deleted `slider_lo.gap`, which fixed that weird bug mentioned above.

```lua
local progress_offset = (pos / 100) * math.abs(pos / 100 - 1)
```

I also deleted this code because it seems not needed anymore since values of 0 are lined up now.

https://github.com/Samillion/ModernZ/blob/06cc6515f0ff000a988cb5a735d914b0aec91991/modernz.lua#L3437-L3440

However, I found another issue, where the handle size was affecting the position of the chapter nibbles. Bigger values like 1 caused the min and max points to be pushed in closer.

![image](https://github.com/user-attachments/assets/bcd44c62-2936-4eb1-bf83-fef3ac906fe3)

**Comment by Samillion** [comment]
> So I deleted `slider_lo.gap`, which fixed that weird bug mentioned above.

😱 y u no make pr?

**Comment by Keith94** [comment]
Welp. I didnt author that code so maybe there was a good reason for it being there. As such there could be a better way to fix? Wasn't sure.

I could make a PR later.

**Comment by Samillion** [comment]
It does indeed improve, but absolute start and end are incorrect with fill.

**Comment by Keith94** [comment]
I guess [7486cbc](https://github.com/Samillion/ModernZ/commit/7486cbcb88bef31f27150091344578e747e3606c) should be reverted until a better workaround is found imo..

**Comment by Samillion** [comment]
> I guess [7486cbc](https://github.com/Samillion/ModernZ/commit/7486cbcb88bef31f27150091344578e747e3606c) should be reverted until a better workaround is found imo..

It's only broken if `handle_always_visible` is set to `no/false`, right?

Should be fine as the default behavior is `yes/true`. Most likely it just needs adjusting in the ranges function for `xp` and `rh` values. I hate math, it makes my tiny brain hurt, that is why I'm delaying looking into it. 😝

**Comment by Keith94** [comment]
>It's only broken if handle_always_visible is set to no/false, right?

It's still broken with `handle_always_visible=yes` as well. I just thought it would be easier to spot when the handle was hidden.

Here is how it looks with seekbarhandlesize=0.4 and handle_always_visible=yes. The progress end goes past the chapter mark.

![mpv_PRlU2SdMEL](https://github.com/user-attachments/assets/c2eadcca-e329-4896-8ba2-b955b0f10931)

**Comment by Samillion** [comment]
> > It's only broken if handle_always_visible is set to no/false, right?
> 
> It's still broken with `handle_always_visible=yes` as well. I just thought it would be easier to spot when the handle was hidden.
> 
> Here is how it looks with seekbarhandlesize=0.4 and handle_always_visible=yes. The progress end goes past the chapter mark.

Ah. You're right. We might need to revert this feature as you said. Though we're in holiday season, so we should give @Xurdejl and @Commander07 ample time if they want to fix their PR before reverting.

**Comment by Keith94** [comment]
Sounds good to me..

Merry Christmas to you and your family as well. 😀

**Comment by Samillion** [comment]
**Test script:** [seekbar_fix/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_seekbar_fix_handle/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/fb18d33f2db2f0cf8f7a2100fd849e033a152126

**Changes:**
- Line up seek range with chapter marker with `handle_always_visible` set to `true` or `false`
- Fix seek progress with `seekbarhandlesize` different values
- Simplify logic for drawing seek ranges

**Known issue:**
If `handle_always_visible` is disabled, the start of progress and end are not correctly presented.

Assuming a 10 minutes video:
- 00:00:00 there is a filled progress
- 00:10:00 there is a gap not filled all the way

![image](https://github.com/user-attachments/assets/a3161ee7-e000-4e32-98a8-93022f34a1fb)

This is obviously compensation for the seek handle.

It should be simple to fix, right? RIGHT? lol. My brain cannot comprehend where the issue is right now.

@Commander07 @Xurdejl help! 😆 I fixed it all except for that one tiny thing. I am certain it's so simple, but my brain is just fried.

**Comment by Samillion** [comment]
@Keith94 I apologize for the bother, but when you have the time, could you please test to confirm that all the issues are fixed except for the known one? No rush at all.

**Comment by Keith94** [comment]
Ye I'll definitely take a look soon 😁

**Comment by Keith94** [comment]
Did you happen to play around with this section at all? Since you mentioned the min/max issue.

https://github.com/Samillion/ModernZ/blob/fb18d33f2db2f0cf8f7a2100fd849e033a152126/modernz.lua#L846-L850

Btw thanks for the efforts.

**Comment by Keith94** [comment]
>Fix seek range with chapter marker whether handle_always_visible is set to true or false
Fix seek progress with seekbarhandlesize different values
Simplify logic for drawing seek ranges

Everything here looks good.

Issue with using `seekbarhandlesize=0` (#199) is still present if we want to support values that low. Unless that's too tricky.

**Comment by Samillion** [comment]
> Everything here looks good.

Awesome!

> Issue with using `seekbarhandlesize=0` (#199) is still present if we want to support values that low. Unless that's too tricky.

The cause of this problem, and the known issue, is that the drawn progress imposes handle as part of the progress.

The fix should be that the handle is an extra, not part of progress, if `handle_always_visible` is disabled or `seekbarhandlesize=0`

The logic of it is so simple, which is making me mad lol. This is what I meant when I said I hate maths 😆 Hopefully the 2 cells in my brain will figure it out.

Either way, I will merge this fix soon even if I don't figure it out, as it does fix issues, however if I don't figure out a fix for the rest of the problems, I won't close this issue until I do.

**Comment by Samillion** [comment]
> Did you happen to play around with this section at all? Since you mentioned the min/max issue.
> 
> https://github.com/Samillion/ModernZ/blob/fb18d33f2db2f0cf8f7a2100fd849e033a152126/modernz.lua#L846-L850
> 
> Btw thanks for the efforts.

You're on to something here. The minimum value always accounts for handle size.

**Comment by Samillion** [comment]
I'm going to show a warning until that known issue is resolved:

```lua
    if not user_opts.handle_always_visible then
        msg.warn("handle_always_visible=no is bugged at the moment and shouldn't be used.")
    end
```

**Comment by Samillion** [comment]
- Merged the fix for the issues into `main`.
- Changed `seekbarhandlesize` min value to `0.1` instead of `0.3`
- Adjusted issue title to reflect the remaining unresolved issue
- Marked resolved/fixed comments after merge to `main`.

**Comment by Keith94** [comment]
Appreciate all the fixes. Looks much better !

Can you temporarily show this comment https://github.com/Samillion/ModernZ/issues/239#issuecomment-2506984312 ? I wanted to check something I added before and I'll hide it again after that.

**Comment by Samillion** [comment]
Done! Sorry about that, no need to hide if it includes essential information.

**Comment by Samillion** [comment]
**Updated:** [seekranges_handlesize/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_seekranges_handlesize/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/b07ba8c2c8e9791522ac3c808f20c1a4bb06a5d9

**Changes:**
- Fix display seek ranges correctly even when `seekbarhandlesize` is set to `0` (ie: no handle)
- Remove `handle_always_visible` option, user can decide whether to have a handle or not by setting the handle size to 0 or more.
- Set a minimum value of `seekbarhandlesize` to 0 instead of 0.1
- Set default value of `seekbarhandlesize` to 0.8

**Comment by Samillion** [comment]
Once fix is confirmed, I'll merge https://github.com/Samillion/ModernZ/pull/292 which will close this issue.

**Comment by Samillion** [comment]
Should `seekbarhandlesize` be renamed to `seek_handle_size`?

**Comment by Samillion** [comment]
**Updated**: [seekranges_handlesize/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_seekranges_handlesize/modernz.lua)
**Commit**: https://github.com/Samillion/ModernZ/commit/0d279ffb5c70996bd008d6965cb64d49a55610d7

**Changes**:
- Rename `seekbarhandlesize` to `seek_handle_size`

**Comment by Keith94** [comment]
Wow, it definitely improved things regarding the min and max points. The filled section no longer goes "out of bounds" at the start like it did before.

I would call it merge-ready but I will point out a minor thing that remains: when you seek somewhere near the start, there is still a small gap in between the cursor position and the edge of the filled section. Probably related to the handle? But at default scale it's pretty easy to miss.

Near beginning:
![image](https://github.com/user-attachments/assets/5370ecc1-bcbd-4393-a9de-8403d6f0a591)

Near end (looks flawless):
![image](https://github.com/user-attachments/assets/ba87e997-f20b-4dd1-8535-f940bf5c34b7)

**Comment by Samillion** [comment]
Nice catch. That is the slider limit, assigned with `slider_lo.border`, which is pixel correct. The issue seems to be with the sliding itself (ie: cursor position at start vs actual position)

The margin of difference though is 1 pixel at the start, I have no idea if this is worth investigating to be honest lol.

**Comment by Keith94** [comment]
Yeah, there's technically a gap even around the halfway point of the file, and seemingly even after that, but towards the end the gap seems to disappear.

But like you mentioned, it's not worth fixing since it's really minor.

**Comment by Samillion** [comment]
**Updated:** [seekranges_handlesize/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_seekranges_handlesize/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/6a9f3353741a3f1a5b12b70ae665af0242b46fe5

**Changes:**
- display seek range more accurately

**2.0 scale**:
https://github.com/user-attachments/assets/0588e146-108a-45d6-91d8-6a55d46e3c7f

![seekranges_pixel_scale](https://github.com/user-attachments/assets/58cfee74-11d3-4e94-837e-8971f3d10ef4)

**Comment by Keith94** [comment]
Excellent. Looks good to me!
