### ISSUE TITLE
osc sometimes breaks completely on startup

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#58]
https://github.com/user-attachments/assets/ab04c980-f56b-4d85-b069-93f58433400d

This one is weird because it's not reproduced consistently. Took me 5 tries above to get it to happen. But I suspect if you set fullscreen=yes in your mpv.conf and have your mouse cursor in a specific spot like I did, the osc will break/doesn't respond to mouse input

I'll try to add better STR later but I don't have time right now

**Comment by Samillion** [comment]
Could you check memory (RAM) spikes? I have a feeling this is due to spikes. Just want to make sure before going deeper.

As in, while trying to reproduce this, keep your eye on cpu/ram/gpu spikes.

Final question, does it happen with all videos or HQ ones only? (ie: 2k+)

My initial gut is telling me this is due to processing, and I bet it will show in `--v` log as a `slow` warning or as a timeout.

**Comment by Samillion** [comment]
Final question, does it happen with stock osc, with the same shaders/config you have?

**Comment by Keith94** [comment]
I'll definitely take a look. Will also go through modernz commit history to check if it's recent

**Comment by Keith94** [comment]
It happens with low bitrate stuff, like vertical videos too. RAM and CPU looks pretty normal to me?

After several attempts it doesn't happen with default OSC. Didn't try other forks though.

Only thing I set with mpv.conf was `fullscreen`.

It seems to happen if you move your mouse cursor at _just the right moment_ in time...
But the osc doesn't completely break.. it still responds to inputs like space bar. I think something is breaking with cursor events or something, because it won't respond to my cursor movement even on first try.


https://github.com/user-attachments/assets/274bad7d-396f-4943-848f-7fc7c0c5a5e4

**Comment by Keith94** [comment]
I also just added `msg-level=all=trace` and `log-file=output.txt` to get the log if that helps:

[output.txt](https://github.com/user-attachments/files/17449013/output.txt)

**Comment by Samillion** [comment]
Noted. Thank you very much for your thorough testing. I'll work on a fix very soon.

**Comment by Samillion** [comment]
Could you try to reproduce it on this version please: 
https://github.com/Samillion/ModernZ/blob/dev_oscnovid/modernz.lua

**Comment by Keith94** [comment]
>https://github.com/Samillion/ModernZ/blob/dev_oscnovid/modernz.lua

I can reproduce, sadly

**Comment by Samillion** [comment]
Does it only happen with bottom hover set to yes?

I apologize for all the questions, I'm unable to re-produce, so I have to rely on statements to try and fix it.

**Comment by Keith94** [comment]
It happens with both yes and no. Trying to get some solid steps for you but it's pretty random

**Comment by Samillion** [comment]
So if I'm understanding this right, with `fullscreen=yes`, sometimes it doesn't detect mouse movement so the OSC doesn't show.

If that happens, then mouse movement doesn't trigger show/hide OSC and all mouse actions stop working? (ie: clicking play/pause)

**Comment by Keith94** [comment]
Yep, that's accurate. Still haven't gotten to why though. Could still be performance related like you mentioned earlier.

**Comment by Samillion** [comment]
Nah, my gut feeling was wrong on that one. Your hardware shouldn't be affected at all by something like this, especially if it's happening happening with ModernZ.

Could you try to reproduce with this one please:
https://github.com/Samillion/ModernZ/blob/dev_oschaltfs_fix/modernz.lua

**Comment by Keith94** [comment]
Can still repro the issue

**Comment by Samillion** [comment]
Sorry for the constant requests, how about this one:
https://github.com/Samillion/ModernZ/blob/dev_oschaltfs_fix/modernz.lua

**Comment by Keith94** [comment]
[output.txt](https://github.com/user-attachments/files/17454635/output.txt)

Can repro around 10% of the time, not sure if improved

**Comment by Samillion** [comment]
Hmmm. I noticed something. osc.lua (built in), is being loaded. 

I have it so it sets osc=no, but I think it's being called too late, because it's readying osc's config for a while.

Could you put `osc=no` in your `mpv.conf` and try please.

**Comment by Samillion** [comment]
```powershell
[   0.008][d][osc] Loading lua script @osc.lua...
[   0.009][d][osc] loading mp.defaults
[   0.009][d][osc] loading @osc.lua
[   0.014][d][osc] reading options for osc
# ...etc
# then in line 213
[   0.014][v][cplayer] Set property: osc="no" -> 1
```

**Comment by Keith94** [comment]
Looks like you're totally correct. As per osc=no I can't reproduce atm

**Comment by Samillion** [comment]
Awesome! Thank you so much for helping me track this down. I'll add a fix very soon.

**Comment by Keith94** [comment]
That's such a relief you noticed that because that bug was so annoying.
```lua
--- Automatically disable OSC
if builtin_osc_enabled then
    mp.set_property_native('osc', false)
end
```
this was [old fork's way](https://github.com/cyl0/ModernX/blob/main/modernx.lua#L213); don't know if that's proper

**Comment by Samillion** [comment]
Yeah, I'm using a similar method (constant observer) so it's always checking if stock osc turns on somehow, then modernz will be like "nu!".

The problem was I had it running late in initiation.

This version should properly disable stock OSC before initiation to avoid conflict. 

If I may bother you yet again, could you try and confirm that it is fixed please:
https://github.com/Samillion/ModernZ/blob/dev_disableosc_properly/modernz.lua

**Comment by Keith94** [comment]
Hmm I can still reproduce with that one

**Comment by Keith94** [comment]
When modernz is functional (no bug), log still shows `[   0.008][d][osc] loading @osc.lua` 
[output.txt](https://github.com/user-attachments/files/17454999/output.txt)

but with osc=no in config, no mention of osc.lua within output.txt

Same for you?

**Comment by Samillion** [comment]
Yeah, even when I place it as the first line, it still triggers osc=no after the actual stock osc is loaded.

I'll apply the fix and leave a note to add osc=no in documentation. Most OSCs do that either way, that's probably why.

**Comment by Keith94** [comment]
Ahh weird. Well that's a shame that it won't play nice with 3rd party osc by default.

Guess I should've kept osc=no all along!
